# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_heartbeats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breathing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_breathing', models.BooleanField()),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
