# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_breathing'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyCrib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Resting', 'resting'), ('Front', 'front'), ('Side', 'side'), ('Vibration', 'vibration')], default='Resting', max_length=10)),
                ('duration', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
