# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_babycrib'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_crying', models.BooleanField()),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='babycrib',
            name='status',
            field=models.CharField(choices=[('resting', 'Resting'), ('front', 'Front'), ('side', 'Side'), ('vibration', 'Vibration')], default='resting', max_length=10),
        ),
    ]
