# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_breathing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breathing',
            name='is_breathing',
        ),
    ]
