# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_breathing_is_breathing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babycrib',
            name='time',
        ),
        migrations.RemoveField(
            model_name='breathing',
            name='time',
        ),
        migrations.RemoveField(
            model_name='heartbeats',
            name='time',
        ),
        migrations.RemoveField(
            model_name='noise',
            name='time',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='time',
        ),
        migrations.AlterField(
            model_name='babycrib',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='breathing',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='heartbeats',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='noise',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
