# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='movement',
            field=models.CharField(default='resting', max_length=10),
        ),
    ]
