sudo: require

language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt

before_script:
  - cd babyonboard/
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - coverage run manage.py test
  - coverage report

after_success:
  - coveralls
