language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt

before_script:
  - python babyonboard/manage.py makemigrations
  - python babyonboard/manage.py migrate

script:
  - python babyonboard/manage.py test api
